server:
  port: 7000
spring:
  application:
    name: crowd-pay
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.13.128
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

ali:
  pay:
    # 支付宝的公钥
    ali-pay-public-key: 
    app-id: # 沙箱的id
    charset: utf-8
    gateway-url: 
    # 应用的私钥
    return-url: http://localhost/pay/return
    sign-type:

